### ISSUE TITLE
Loading via Composer

### ISSUE THREAD

**Issue by sebastianwahn** [claviska/simple-php-captcha#19]
Can you add a composer.json and/or add your package to packagist?
Then your package can be installed via the package manager composer.

Currently this is not possible, even not when adding you library to composer via repositories reference, because it can not find a composer.json file in your repository.

**Comment by wilfred-arambhan** [comment]
Is this package added in packagist? I'm not able to load the package via composer.

**Comment by claviska** [comment]
Added now. Thanks.
