### ISSUE TITLE
something's wrong with generating image path

### ISSUE THREAD

**Issue by mevsme** [claviska/simple-php-captcha#22]
my path is `/media/mvm/Home/Dropbox/Privat/Programming/PHP/site.com/www/vendor/simple-php-captcha-master`

but `$image_src` becomes `/e/Dropbox/Privat/Programming/PHP/site.com/www/vendor/simple-php-captcha-master/simple-php-captcha.php`

**Comment by claviska** [comment]
It's using the [realpath](http://php.net/manual/en/function.realpath.php), so that might be what you're seeing.

The image source should be relative to the website root so you can use it in a URL. It shouldn't contain an absolute path, as that wouldn't be very useful to the browser.

**Comment by claviska** [comment]
Duplicate of #21
