### ISSUE TITLE
Image disappears 

### ISSUE THREAD

**Issue by falconxxx** [claviska/simple-php-captcha#26]
I have been using the captcha for a while now with no itch, but later I discovered that it doesn't work well on mobile phones it disappears after a few seconds of page load but works well on the desktop .
How do I go about this?

**Comment by claviska** [comment]
Sounds like a browser bug, to be honest. No way I can even guess how to fix that without seeing an example.

**Comment by falconxxx** [comment]
Issue resolved, Thank you for speedy response though.
All I had to do was disable retina.js
