### ISSUE TITLE
captcha create wrong image.!

### ISSUE THREAD

**Issue by mboveiri** [claviska/simple-php-captcha#27]
Hi.
It seems that captcha create wrong image : 

![wrong](https://user-images.githubusercontent.com/4364319/28784982-4724a04c-762a-11e7-8fff-e40181031e7f.png)

the text is result of : `echo $_SESSION['captcha']['code'];` and its different from the created photo by captcha.

**Comment by claviska** [comment]
The image gets created and the code gets stored in `$_SESSION['captcha']['code']` immediately after. Make sure you're calling `session_start()` and that you haven't made subsequent calls or changed the session variable elsewhere.

**Comment by mboveiri** [comment]
find the solution; `session_start();` must be used after ` include("simple-php-captcha.php")` cause another `session_start();` exist on `simple-php-captcha.php` and overlay the current session.
