### ISSUE TITLE
Undefined index "_CAPTCHA"

### ISSUE THREAD

**Issue by nathan815** [claviska/simple-php-captcha#8]
I'm having an issue. The image isn't showing up and when I view the image URL I get this error:

_Notice: Undefined index: _CAPTCHA in /Applications/MAMP/htdocs/gifsite/plugins/captcha/simple-php-captcha.php on line 113_

Not sure what's going on here, but it looks like it's something wrong with the code for simple-php-captcha.

Thanks,
Nathan

**Comment by emxjay** [comment]
Hi - I have the same issue here. Regardless of the notice, the image itself never shows up.

This was tested on [the last version](https://github.com/claviska/simple-php-captcha/commit/9d65a945029c7be7bb6bc893759e74c5636be694) of the script (with PHP GD v2.1.0).
